"""Typed isolation-kernel contracts.

The package owns runtime-boundary mechanics while callers retain policy,
diagnostic wording, and verdict composition.
"""

from evoom_guard.isolation.candidate import (
    CANDIDATE_CID_DIRNAME,
    CandidateRunner,
    IsolationEvidence,
    IsolationUnavailable,
)
from evoom_guard.isolation.docker import (
    DOCKER_CLEANUP_RECONCILE_ATTEMPTS,
    DOCKER_CLEANUP_RECONCILE_INTERVAL_SECONDS,
    DOCKER_CLEANUP_REQUIRED_FINAL_ABSENT_OBSERVATIONS,
    DOCKER_CLEANUP_TOTAL_TIMEOUT_SECONDS,
    DOCKER_CONTROL_TIMEOUT_SECONDS,
    DOCKER_PULL_TIMEOUT_SECONDS,
    DockerCandidateCleanupRequest,
    DockerCandidateCleanupResult,
    DockerCidScanResult,
    DockerContainerAbsenceObservation,
    DockerContainerCleanupResult,
    DockerContainerProbe,
    DockerControlRequest,
    DockerControlResult,
    DockerImageResolution,
    DockerRunContainmentError,
    DockerRunOutputLimit,
    DockerRunRequest,
    DockerRunTimeout,
    cleanup_candidate_containers,
    cleanup_named_container,
    docker_container_name,
    execute_docker_control,
    inspect_docker_image,
    probe_container_absent,
    probe_container_started,
    resolve_docker_image,
    run_named_docker_client,
    scan_candidate_container_ids,
)
from evoom_guard.isolation.invocation import InvocationRecorder

__all__ = [
    "CANDIDATE_CID_DIRNAME",
    "DOCKER_CLEANUP_RECONCILE_ATTEMPTS",
    "DOCKER_CLEANUP_RECONCILE_INTERVAL_SECONDS",
    "DOCKER_CLEANUP_REQUIRED_FINAL_ABSENT_OBSERVATIONS",
    "DOCKER_CLEANUP_TOTAL_TIMEOUT_SECONDS",
    "DOCKER_CONTROL_TIMEOUT_SECONDS",
    "DOCKER_PULL_TIMEOUT_SECONDS",
    "DockerCandidateCleanupRequest",
    "DockerCandidateCleanupResult",
    "DockerCidScanResult",
    "DockerContainerAbsenceObservation",
    "DockerContainerCleanupResult",
    "DockerContainerProbe",
    "DockerControlRequest",
    "DockerControlResult",
    "DockerImageResolution",
    "DockerRunContainmentError",
    "DockerRunOutputLimit",
    "DockerRunRequest",
    "DockerRunTimeout",
    "CandidateRunner",
    "IsolationEvidence",
    "IsolationUnavailable",
    "InvocationRecorder",
    "cleanup_candidate_containers",
    "cleanup_named_container",
    "docker_container_name",
    "execute_docker_control",
    "inspect_docker_image",
    "probe_container_absent",
    "probe_container_started",
    "resolve_docker_image",
    "run_named_docker_client",
    "scan_candidate_container_ids",
]
